### PR TITLE
add macro generating function updating single element in tuple

### PR DESCRIPTION
**Pull request by ryskajakub**
Hi, I needed a one more function that I was missing in the api, so I created it, are you interested in having it in the project? If yes I can try to fit it in the style and then you can merge it.

### CODE REVIEW

**Comment by DanielSchuessler** [comment]
Thanks, and sorry for the late response. Yes, I think this would be a useful function for this this library.

**Comment by ryskajakub** [comment]
No problem. Shall I do any changes in the implementation or naming or it is good as it is?

**Comment by DanielSchuessler** [comment]
I made some small changes (e9de7cd58fbcea8fc33f26fa9b45d0e7120b429f) (Haddock, used the `withxs` helper function for validation of the length parameter and for consistency, added validation of the index parameter).

**Comment by ryskajakub** [comment]
Can you, please, upload a new version with this change to hackage?

**Comment by DanielSchuessler** [comment]
Done.

**Comment by ryskajakub** [comment]
Thanks!

**Pull request merged**
